

class ParserEngineException(Exception):
    ...

class BreakParseProcessing(ParserEngineException):
    ...

class BaseUrlNotFound(ParserEngineException):
    ...

class MetaException(ParserEngineException):
    ...